name: Feature Request
description: Suggest an idea for the JLR InControl integration
title: "[Feature]: "
labels:
  - enhancement
assignees:
  - willbeeching
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem would this solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to happen?
    validations:
      required: true

  - type: input
    id: vehicle
    attributes:
      label: Vehicle
      placeholder: e.g. Land Rover Defender 2023 (PHEV), Jaguar I-PACE 2021
    validations:
      required: false
